version: '3.8'

services:
  # Redis servisi
  redis:
    image: redis:alpine
    container_name: pillow-robot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Flask API servisi
  api:
    build: .
    container_name: pillow-robot-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://localhost:3000}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./instance:/app/instance

  # Nginx reverse proxy (opsiyonel)
  nginx:
    image: nginx:alpine
    container_name: pillow-robot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis_data: 